obj-m := rack_dm.o rack_vm.o rack_block.o rack_dvs_rdma.o rack_dvs_dram.o rack_dvs.o krdma.o

ccflags-y := -I$(src)/include

rack_dm-y := rack_dm/rack_dm.o rack_dm/ioctl.o rack_dm/fault.o rack_dm/region.o rack_dm/rdma.o rack_dm/rpc.o

rack_vm-y := rack_vm/rack_vm.o rack_vm/fault.o rack_vm/region.o

rack_block-y := rack_block/null_blk_main.o rack_block/null_blk_zoned.o

rack_dvs_rdma-y := rack_dvs/rdma_backend.o rack_dvs/test.o

rack_dvs_dram-y := rack_dvs/dram_backend.o rack_dvs/test.o

rack_dvs-y := rack_dvs/rack_dvs.o

krdma-y := krdma/krdma.o krdma/cm.o krdma/ioctl.o krdma/dbgfs.o krdma/rpc.o krdma/rdma.o krdma/benchmark.o
